"use client";

import { useState, useEffect } from "react";

const C = {
  cardBg: "#1E293B",
  border: "#334155",
  text: "#F1F5F9",
  textMuted: "#94A3B8",
  accent: "#3B82F6",
  success: "#10B981",
  danger: "#EF4444",
  warning: "#F59E0B",
};

const DOC_TYPE_LABELS: Record<string, string> = {
  status_report: "Status Report",
  risk_memo: "Risk Memo",
  task_report: "Task Report",
  csv_export: "CSV Export",
  custom: "Custom",
};

interface Doc {
  id: string;
  docType: string;
  title: string;
  blobUrl: string;
  previewText: string | null;
  format: string;
  wordCount: number | null;
  createdAt: string;
}

interface Props {
  dealId: string;
}

export default function AgentDocumentsPanel({ dealId }: Props) {
  const [docs, setDocs] = useState<Doc[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [previewDoc, setPreviewDoc] = useState<Doc | null>(null);
  const [deletingId, setDeletingId] = useState<string | null>(null);

  useEffect(() => { load(); }, [dealId]);

  async function load() {
    setLoading(true);
    try {
      const res = await fetch(`/api/agent/documents?dealId=${dealId}`);
      const d = await res.json();
      setDocs(
        (d.documents ?? []).map((doc: any) => ({
          id: doc.id,
          docType: doc.doc_type,
          title: doc.title,
          blobUrl: doc.blob_url,
          previewText: doc.preview_text,
          format: doc.format,
          wordCount: doc.word_count,
          createdAt: doc.created_at,
        }))
      );
    } catch {
      setError("Failed to load documents.");
    } finally {
      setLoading(false);
    }
  }

  async function deleteDoc(id: string, blobUrl: string) {
    if (!confirm("Delete this document? This cannot be undone.")) return;
    setDeletingId(id);
    try {
      await fetch(`/api/agent/documents?id=${id}&blobUrl=${encodeURIComponent(blobUrl)}`, { method: "DELETE" });
      setDocs((prev) => prev.filter((d) => d.id !== id));
      if (previewDoc?.id === id) setPreviewDoc(null);
    } catch {
      setError("Delete failed.");
    } finally {
      setDeletingId(null);
    }
  }

  function formatDate(iso: string) {
    return new Date(iso).toLocaleDateString("en-US", { month: "short", day: "numeric", year: "numeric", hour: "2-digit", minute: "2-digit" });
  }

  if (loading) {
    return <div style={{ padding: 40, textAlign: "center", color: C.textMuted, fontSize: 13 }}>Loading documents…</div>;
  }

  return (
    <div style={{ display: "flex", gap: 16, height: "100%" }}>
      {/* Document list */}
      <div style={{ flex: previewDoc ? "0 0 340px" : 1, display: "flex", flexDirection: "column", gap: 8 }}>
        <div style={{ marginBottom: 8 }}>
          <div style={{ fontSize: 14, fontWeight: 700, color: C.text, marginBottom: 2 }}>Synthesized Documents</div>
          <div style={{ fontSize: 12, color: C.textMuted }}>Documents generated by the agent. Click to preview or download.</div>
        </div>

        {error && (
          <div style={{ padding: "8px 12px", background: "#3B0F0F", border: `1px solid ${C.danger}55`, borderRadius: 8, color: "#FCA5A5", fontSize: 12 }}>
            {error} <button onClick={() => setError(null)} style={{ background: "none", border: "none", color: "#FCA5A5", cursor: "pointer", marginLeft: 8 }}>×</button>
          </div>
        )}

        {docs.length === 0 ? (
          <div style={{ padding: 32, textAlign: "center", color: C.textMuted, fontSize: 13 }}>
            No documents yet. Ask the agent to "generate a status report" to create one.
          </div>
        ) : (
          docs.map((doc) => (
            <div
              key={doc.id}
              style={{
                padding: "12px 14px", borderRadius: 10,
                background: previewDoc?.id === doc.id ? `${C.accent}11` : C.cardBg,
                border: `1px solid ${previewDoc?.id === doc.id ? C.accent : C.border}`,
                cursor: "pointer",
                transition: "border-color 0.15s",
              }}
              onClick={() => setPreviewDoc(previewDoc?.id === doc.id ? null : doc)}
            >
              <div style={{ display: "flex", alignItems: "flex-start", justifyContent: "space-between", gap: 8 }}>
                <div style={{ flex: 1, minWidth: 0 }}>
                  <div style={{ display: "flex", alignItems: "center", gap: 6, marginBottom: 4, flexWrap: "wrap" }}>
                    <span style={{ fontSize: 11, padding: "1px 7px", borderRadius: 10, background: `${C.accent}22`, color: C.accent, fontWeight: 600, flexShrink: 0 }}>
                      {DOC_TYPE_LABELS[doc.docType] ?? doc.docType}
                    </span>
                    <span style={{ fontSize: 10, color: C.textMuted, flexShrink: 0 }}>
                      {doc.format.toUpperCase()} {doc.wordCount ? `· ${doc.wordCount}w` : ""}
                    </span>
                  </div>
                  <div style={{ fontSize: 13, fontWeight: 600, color: C.text, marginBottom: 2, overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap" }}>
                    {doc.title}
                  </div>
                  <div style={{ fontSize: 11, color: C.textMuted }}>{formatDate(doc.createdAt)}</div>
                </div>
                <div style={{ display: "flex", gap: 5, flexShrink: 0 }}>
                  <a
                    href={doc.blobUrl}
                    download
                    onClick={(e) => e.stopPropagation()}
                    style={{
                      padding: "4px 10px", borderRadius: 6, border: `1px solid ${C.border}`,
                      background: "transparent", color: C.textMuted, fontSize: 11,
                      textDecoration: "none", display: "inline-flex", alignItems: "center",
                    }}
                  >
                    ↓
                  </a>
                  <button
                    onClick={(e) => { e.stopPropagation(); deleteDoc(doc.id, doc.blobUrl); }}
                    disabled={deletingId === doc.id}
                    style={{
                      padding: "4px 10px", borderRadius: 6, border: `1px solid ${C.danger}44`,
                      background: "transparent", color: C.danger, fontSize: 11, cursor: "pointer",
                      opacity: deletingId === doc.id ? 0.5 : 1,
                    }}
                  >
                    ×
                  </button>
                </div>
              </div>
            </div>
          ))
        )}
      </div>

      {/* Preview pane */}
      {previewDoc && (
        <div style={{
          flex: 1, display: "flex", flexDirection: "column",
          background: C.cardBg, borderRadius: 10, border: `1px solid ${C.border}`,
          overflow: "hidden",
        }}>
          <div style={{
            padding: "12px 16px", borderBottom: `1px solid ${C.border}`,
            display: "flex", alignItems: "center", justifyContent: "space-between",
          }}>
            <div style={{ fontSize: 13, fontWeight: 600, color: C.text }}>{previewDoc.title}</div>
            <button
              onClick={() => setPreviewDoc(null)}
              style={{ background: "none", border: "none", color: C.textMuted, cursor: "pointer", fontSize: 16 }}
            >
              ×
            </button>
          </div>
          <div style={{ flex: 1, overflowY: "auto", padding: 16 }}>
            {previewDoc.previewText ? (
              <pre style={{
                fontSize: 12, color: C.textMuted, whiteSpace: "pre-wrap",
                wordBreak: "break-word", lineHeight: 1.6, fontFamily: "inherit", margin: 0,
              }}>
                {previewDoc.previewText}
                {previewDoc.wordCount && previewDoc.wordCount > 80 && (
                  <span style={{ color: C.accent }}>
                    {"\n\n"}[Preview truncated — download for full document]
                  </span>
                )}
              </pre>
            ) : (
              <div style={{ color: C.textMuted, fontSize: 12 }}>No preview available. Download to view.</div>
            )}
          </div>
          <div style={{ padding: "10px 16px", borderTop: `1px solid ${C.border}` }}>
            <a
              href={previewDoc.blobUrl}
              download
              style={{
                display: "inline-block", padding: "7px 16px", borderRadius: 8,
                background: C.accent, color: "#fff", fontSize: 12, fontWeight: 600,
                textDecoration: "none",
              }}
            >
              Download {previewDoc.format.toUpperCase()}
            </a>
          </div>
        </div>
      )}
    </div>
  );
}
